// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/slimeyquest/server/ent/player"
	"github.com/slimeyquest/server/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePlayer = "Player"
)

// PlayerMutation represents an operation that mutates the Player nodes in the graph.
type PlayerMutation struct {
	config
	op                       Op
	typ                      string
	id                       *int
	platform                 *string
	external_id              *string
	nickname                 *string
	level                    *int32
	addlevel                 *int32
	exp                      *int64
	addexp                   *int64
	created_at               *time.Time
	updated_at               *time.Time
	last_login_at            *time.Time
	gold                     *int64
	addgold                  *int64
	gems                     *int64
	addgems                  *int64
	adventure_id             *int32
	addadventure_id          *int32
	stage_index              *int32
	addstage_index           *int32
	highest_stage_cleared    *int32
	addhighest_stage_cleared *int32
	last_claim_at            *time.Time
	equipment_json           *map[string]interface{}
	cleared_milestones       *[]int32
	appendcleared_milestones []int32
	clearedFields            map[string]struct{}
	done                     bool
	oldValue                 func(context.Context) (*Player, error)
	predicates               []predicate.Player
}

var _ ent.Mutation = (*PlayerMutation)(nil)

// playerOption allows management of the mutation configuration using functional options.
type playerOption func(*PlayerMutation)

// newPlayerMutation creates new mutation for the Player entity.
func newPlayerMutation(c config, op Op, opts ...playerOption) *PlayerMutation {
	m := &PlayerMutation{
		config:        c,
		op:            op,
		typ:           TypePlayer,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPlayerID sets the ID field of the mutation.
func withPlayerID(id int) playerOption {
	return func(m *PlayerMutation) {
		var (
			err   error
			once  sync.Once
			value *Player
		)
		m.oldValue = func(ctx context.Context) (*Player, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Player.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPlayer sets the old Player of the mutation.
func withPlayer(node *Player) playerOption {
	return func(m *PlayerMutation) {
		m.oldValue = func(context.Context) (*Player, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PlayerMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PlayerMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PlayerMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PlayerMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Player.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPlatform sets the "platform" field.
func (m *PlayerMutation) SetPlatform(s string) {
	m.platform = &s
}

// Platform returns the value of the "platform" field in the mutation.
func (m *PlayerMutation) Platform() (r string, exists bool) {
	v := m.platform
	if v == nil {
		return
	}
	return *v, true
}

// OldPlatform returns the old "platform" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldPlatform(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPlatform is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPlatform requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPlatform: %w", err)
	}
	return oldValue.Platform, nil
}

// ResetPlatform resets all changes to the "platform" field.
func (m *PlayerMutation) ResetPlatform() {
	m.platform = nil
}

// SetExternalID sets the "external_id" field.
func (m *PlayerMutation) SetExternalID(s string) {
	m.external_id = &s
}

// ExternalID returns the value of the "external_id" field in the mutation.
func (m *PlayerMutation) ExternalID() (r string, exists bool) {
	v := m.external_id
	if v == nil {
		return
	}
	return *v, true
}

// OldExternalID returns the old "external_id" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldExternalID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExternalID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExternalID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExternalID: %w", err)
	}
	return oldValue.ExternalID, nil
}

// ResetExternalID resets all changes to the "external_id" field.
func (m *PlayerMutation) ResetExternalID() {
	m.external_id = nil
}

// SetNickname sets the "nickname" field.
func (m *PlayerMutation) SetNickname(s string) {
	m.nickname = &s
}

// Nickname returns the value of the "nickname" field in the mutation.
func (m *PlayerMutation) Nickname() (r string, exists bool) {
	v := m.nickname
	if v == nil {
		return
	}
	return *v, true
}

// OldNickname returns the old "nickname" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldNickname(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNickname is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNickname requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNickname: %w", err)
	}
	return oldValue.Nickname, nil
}

// ResetNickname resets all changes to the "nickname" field.
func (m *PlayerMutation) ResetNickname() {
	m.nickname = nil
}

// SetLevel sets the "level" field.
func (m *PlayerMutation) SetLevel(i int32) {
	m.level = &i
	m.addlevel = nil
}

// Level returns the value of the "level" field in the mutation.
func (m *PlayerMutation) Level() (r int32, exists bool) {
	v := m.level
	if v == nil {
		return
	}
	return *v, true
}

// OldLevel returns the old "level" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldLevel(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLevel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLevel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLevel: %w", err)
	}
	return oldValue.Level, nil
}

// AddLevel adds i to the "level" field.
func (m *PlayerMutation) AddLevel(i int32) {
	if m.addlevel != nil {
		*m.addlevel += i
	} else {
		m.addlevel = &i
	}
}

// AddedLevel returns the value that was added to the "level" field in this mutation.
func (m *PlayerMutation) AddedLevel() (r int32, exists bool) {
	v := m.addlevel
	if v == nil {
		return
	}
	return *v, true
}

// ResetLevel resets all changes to the "level" field.
func (m *PlayerMutation) ResetLevel() {
	m.level = nil
	m.addlevel = nil
}

// SetExp sets the "exp" field.
func (m *PlayerMutation) SetExp(i int64) {
	m.exp = &i
	m.addexp = nil
}

// Exp returns the value of the "exp" field in the mutation.
func (m *PlayerMutation) Exp() (r int64, exists bool) {
	v := m.exp
	if v == nil {
		return
	}
	return *v, true
}

// OldExp returns the old "exp" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldExp(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExp: %w", err)
	}
	return oldValue.Exp, nil
}

// AddExp adds i to the "exp" field.
func (m *PlayerMutation) AddExp(i int64) {
	if m.addexp != nil {
		*m.addexp += i
	} else {
		m.addexp = &i
	}
}

// AddedExp returns the value that was added to the "exp" field in this mutation.
func (m *PlayerMutation) AddedExp() (r int64, exists bool) {
	v := m.addexp
	if v == nil {
		return
	}
	return *v, true
}

// ResetExp resets all changes to the "exp" field.
func (m *PlayerMutation) ResetExp() {
	m.exp = nil
	m.addexp = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *PlayerMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *PlayerMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *PlayerMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *PlayerMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *PlayerMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *PlayerMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetLastLoginAt sets the "last_login_at" field.
func (m *PlayerMutation) SetLastLoginAt(t time.Time) {
	m.last_login_at = &t
}

// LastLoginAt returns the value of the "last_login_at" field in the mutation.
func (m *PlayerMutation) LastLoginAt() (r time.Time, exists bool) {
	v := m.last_login_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastLoginAt returns the old "last_login_at" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldLastLoginAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastLoginAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastLoginAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastLoginAt: %w", err)
	}
	return oldValue.LastLoginAt, nil
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (m *PlayerMutation) ClearLastLoginAt() {
	m.last_login_at = nil
	m.clearedFields[player.FieldLastLoginAt] = struct{}{}
}

// LastLoginAtCleared returns if the "last_login_at" field was cleared in this mutation.
func (m *PlayerMutation) LastLoginAtCleared() bool {
	_, ok := m.clearedFields[player.FieldLastLoginAt]
	return ok
}

// ResetLastLoginAt resets all changes to the "last_login_at" field.
func (m *PlayerMutation) ResetLastLoginAt() {
	m.last_login_at = nil
	delete(m.clearedFields, player.FieldLastLoginAt)
}

// SetGold sets the "gold" field.
func (m *PlayerMutation) SetGold(i int64) {
	m.gold = &i
	m.addgold = nil
}

// Gold returns the value of the "gold" field in the mutation.
func (m *PlayerMutation) Gold() (r int64, exists bool) {
	v := m.gold
	if v == nil {
		return
	}
	return *v, true
}

// OldGold returns the old "gold" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldGold(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGold is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGold requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGold: %w", err)
	}
	return oldValue.Gold, nil
}

// AddGold adds i to the "gold" field.
func (m *PlayerMutation) AddGold(i int64) {
	if m.addgold != nil {
		*m.addgold += i
	} else {
		m.addgold = &i
	}
}

// AddedGold returns the value that was added to the "gold" field in this mutation.
func (m *PlayerMutation) AddedGold() (r int64, exists bool) {
	v := m.addgold
	if v == nil {
		return
	}
	return *v, true
}

// ResetGold resets all changes to the "gold" field.
func (m *PlayerMutation) ResetGold() {
	m.gold = nil
	m.addgold = nil
}

// SetGems sets the "gems" field.
func (m *PlayerMutation) SetGems(i int64) {
	m.gems = &i
	m.addgems = nil
}

// Gems returns the value of the "gems" field in the mutation.
func (m *PlayerMutation) Gems() (r int64, exists bool) {
	v := m.gems
	if v == nil {
		return
	}
	return *v, true
}

// OldGems returns the old "gems" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldGems(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGems is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGems requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGems: %w", err)
	}
	return oldValue.Gems, nil
}

// AddGems adds i to the "gems" field.
func (m *PlayerMutation) AddGems(i int64) {
	if m.addgems != nil {
		*m.addgems += i
	} else {
		m.addgems = &i
	}
}

// AddedGems returns the value that was added to the "gems" field in this mutation.
func (m *PlayerMutation) AddedGems() (r int64, exists bool) {
	v := m.addgems
	if v == nil {
		return
	}
	return *v, true
}

// ResetGems resets all changes to the "gems" field.
func (m *PlayerMutation) ResetGems() {
	m.gems = nil
	m.addgems = nil
}

// SetAdventureID sets the "adventure_id" field.
func (m *PlayerMutation) SetAdventureID(i int32) {
	m.adventure_id = &i
	m.addadventure_id = nil
}

// AdventureID returns the value of the "adventure_id" field in the mutation.
func (m *PlayerMutation) AdventureID() (r int32, exists bool) {
	v := m.adventure_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAdventureID returns the old "adventure_id" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldAdventureID(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAdventureID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAdventureID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAdventureID: %w", err)
	}
	return oldValue.AdventureID, nil
}

// AddAdventureID adds i to the "adventure_id" field.
func (m *PlayerMutation) AddAdventureID(i int32) {
	if m.addadventure_id != nil {
		*m.addadventure_id += i
	} else {
		m.addadventure_id = &i
	}
}

// AddedAdventureID returns the value that was added to the "adventure_id" field in this mutation.
func (m *PlayerMutation) AddedAdventureID() (r int32, exists bool) {
	v := m.addadventure_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetAdventureID resets all changes to the "adventure_id" field.
func (m *PlayerMutation) ResetAdventureID() {
	m.adventure_id = nil
	m.addadventure_id = nil
}

// SetStageIndex sets the "stage_index" field.
func (m *PlayerMutation) SetStageIndex(i int32) {
	m.stage_index = &i
	m.addstage_index = nil
}

// StageIndex returns the value of the "stage_index" field in the mutation.
func (m *PlayerMutation) StageIndex() (r int32, exists bool) {
	v := m.stage_index
	if v == nil {
		return
	}
	return *v, true
}

// OldStageIndex returns the old "stage_index" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldStageIndex(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStageIndex is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStageIndex requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStageIndex: %w", err)
	}
	return oldValue.StageIndex, nil
}

// AddStageIndex adds i to the "stage_index" field.
func (m *PlayerMutation) AddStageIndex(i int32) {
	if m.addstage_index != nil {
		*m.addstage_index += i
	} else {
		m.addstage_index = &i
	}
}

// AddedStageIndex returns the value that was added to the "stage_index" field in this mutation.
func (m *PlayerMutation) AddedStageIndex() (r int32, exists bool) {
	v := m.addstage_index
	if v == nil {
		return
	}
	return *v, true
}

// ResetStageIndex resets all changes to the "stage_index" field.
func (m *PlayerMutation) ResetStageIndex() {
	m.stage_index = nil
	m.addstage_index = nil
}

// SetHighestStageCleared sets the "highest_stage_cleared" field.
func (m *PlayerMutation) SetHighestStageCleared(i int32) {
	m.highest_stage_cleared = &i
	m.addhighest_stage_cleared = nil
}

// HighestStageCleared returns the value of the "highest_stage_cleared" field in the mutation.
func (m *PlayerMutation) HighestStageCleared() (r int32, exists bool) {
	v := m.highest_stage_cleared
	if v == nil {
		return
	}
	return *v, true
}

// OldHighestStageCleared returns the old "highest_stage_cleared" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldHighestStageCleared(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHighestStageCleared is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHighestStageCleared requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHighestStageCleared: %w", err)
	}
	return oldValue.HighestStageCleared, nil
}

// AddHighestStageCleared adds i to the "highest_stage_cleared" field.
func (m *PlayerMutation) AddHighestStageCleared(i int32) {
	if m.addhighest_stage_cleared != nil {
		*m.addhighest_stage_cleared += i
	} else {
		m.addhighest_stage_cleared = &i
	}
}

// AddedHighestStageCleared returns the value that was added to the "highest_stage_cleared" field in this mutation.
func (m *PlayerMutation) AddedHighestStageCleared() (r int32, exists bool) {
	v := m.addhighest_stage_cleared
	if v == nil {
		return
	}
	return *v, true
}

// ResetHighestStageCleared resets all changes to the "highest_stage_cleared" field.
func (m *PlayerMutation) ResetHighestStageCleared() {
	m.highest_stage_cleared = nil
	m.addhighest_stage_cleared = nil
}

// SetLastClaimAt sets the "last_claim_at" field.
func (m *PlayerMutation) SetLastClaimAt(t time.Time) {
	m.last_claim_at = &t
}

// LastClaimAt returns the value of the "last_claim_at" field in the mutation.
func (m *PlayerMutation) LastClaimAt() (r time.Time, exists bool) {
	v := m.last_claim_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastClaimAt returns the old "last_claim_at" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldLastClaimAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastClaimAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastClaimAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastClaimAt: %w", err)
	}
	return oldValue.LastClaimAt, nil
}

// ClearLastClaimAt clears the value of the "last_claim_at" field.
func (m *PlayerMutation) ClearLastClaimAt() {
	m.last_claim_at = nil
	m.clearedFields[player.FieldLastClaimAt] = struct{}{}
}

// LastClaimAtCleared returns if the "last_claim_at" field was cleared in this mutation.
func (m *PlayerMutation) LastClaimAtCleared() bool {
	_, ok := m.clearedFields[player.FieldLastClaimAt]
	return ok
}

// ResetLastClaimAt resets all changes to the "last_claim_at" field.
func (m *PlayerMutation) ResetLastClaimAt() {
	m.last_claim_at = nil
	delete(m.clearedFields, player.FieldLastClaimAt)
}

// SetEquipmentJSON sets the "equipment_json" field.
func (m *PlayerMutation) SetEquipmentJSON(value map[string]interface{}) {
	m.equipment_json = &value
}

// EquipmentJSON returns the value of the "equipment_json" field in the mutation.
func (m *PlayerMutation) EquipmentJSON() (r map[string]interface{}, exists bool) {
	v := m.equipment_json
	if v == nil {
		return
	}
	return *v, true
}

// OldEquipmentJSON returns the old "equipment_json" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldEquipmentJSON(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEquipmentJSON is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEquipmentJSON requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEquipmentJSON: %w", err)
	}
	return oldValue.EquipmentJSON, nil
}

// ResetEquipmentJSON resets all changes to the "equipment_json" field.
func (m *PlayerMutation) ResetEquipmentJSON() {
	m.equipment_json = nil
}

// SetClearedMilestones sets the "cleared_milestones" field.
func (m *PlayerMutation) SetClearedMilestones(i []int32) {
	m.cleared_milestones = &i
	m.appendcleared_milestones = nil
}

// ClearedMilestones returns the value of the "cleared_milestones" field in the mutation.
func (m *PlayerMutation) ClearedMilestones() (r []int32, exists bool) {
	v := m.cleared_milestones
	if v == nil {
		return
	}
	return *v, true
}

// OldClearedMilestones returns the old "cleared_milestones" field's value of the Player entity.
// If the Player object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PlayerMutation) OldClearedMilestones(ctx context.Context) (v []int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClearedMilestones is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClearedMilestones requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClearedMilestones: %w", err)
	}
	return oldValue.ClearedMilestones, nil
}

// AppendClearedMilestones adds i to the "cleared_milestones" field.
func (m *PlayerMutation) AppendClearedMilestones(i []int32) {
	m.appendcleared_milestones = append(m.appendcleared_milestones, i...)
}

// AppendedClearedMilestones returns the list of values that were appended to the "cleared_milestones" field in this mutation.
func (m *PlayerMutation) AppendedClearedMilestones() ([]int32, bool) {
	if len(m.appendcleared_milestones) == 0 {
		return nil, false
	}
	return m.appendcleared_milestones, true
}

// ResetClearedMilestones resets all changes to the "cleared_milestones" field.
func (m *PlayerMutation) ResetClearedMilestones() {
	m.cleared_milestones = nil
	m.appendcleared_milestones = nil
}

// Where appends a list predicates to the PlayerMutation builder.
func (m *PlayerMutation) Where(ps ...predicate.Player) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PlayerMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PlayerMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Player, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PlayerMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PlayerMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Player).
func (m *PlayerMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PlayerMutation) Fields() []string {
	fields := make([]string, 0, 16)
	if m.platform != nil {
		fields = append(fields, player.FieldPlatform)
	}
	if m.external_id != nil {
		fields = append(fields, player.FieldExternalID)
	}
	if m.nickname != nil {
		fields = append(fields, player.FieldNickname)
	}
	if m.level != nil {
		fields = append(fields, player.FieldLevel)
	}
	if m.exp != nil {
		fields = append(fields, player.FieldExp)
	}
	if m.created_at != nil {
		fields = append(fields, player.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, player.FieldUpdatedAt)
	}
	if m.last_login_at != nil {
		fields = append(fields, player.FieldLastLoginAt)
	}
	if m.gold != nil {
		fields = append(fields, player.FieldGold)
	}
	if m.gems != nil {
		fields = append(fields, player.FieldGems)
	}
	if m.adventure_id != nil {
		fields = append(fields, player.FieldAdventureID)
	}
	if m.stage_index != nil {
		fields = append(fields, player.FieldStageIndex)
	}
	if m.highest_stage_cleared != nil {
		fields = append(fields, player.FieldHighestStageCleared)
	}
	if m.last_claim_at != nil {
		fields = append(fields, player.FieldLastClaimAt)
	}
	if m.equipment_json != nil {
		fields = append(fields, player.FieldEquipmentJSON)
	}
	if m.cleared_milestones != nil {
		fields = append(fields, player.FieldClearedMilestones)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PlayerMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case player.FieldPlatform:
		return m.Platform()
	case player.FieldExternalID:
		return m.ExternalID()
	case player.FieldNickname:
		return m.Nickname()
	case player.FieldLevel:
		return m.Level()
	case player.FieldExp:
		return m.Exp()
	case player.FieldCreatedAt:
		return m.CreatedAt()
	case player.FieldUpdatedAt:
		return m.UpdatedAt()
	case player.FieldLastLoginAt:
		return m.LastLoginAt()
	case player.FieldGold:
		return m.Gold()
	case player.FieldGems:
		return m.Gems()
	case player.FieldAdventureID:
		return m.AdventureID()
	case player.FieldStageIndex:
		return m.StageIndex()
	case player.FieldHighestStageCleared:
		return m.HighestStageCleared()
	case player.FieldLastClaimAt:
		return m.LastClaimAt()
	case player.FieldEquipmentJSON:
		return m.EquipmentJSON()
	case player.FieldClearedMilestones:
		return m.ClearedMilestones()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PlayerMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case player.FieldPlatform:
		return m.OldPlatform(ctx)
	case player.FieldExternalID:
		return m.OldExternalID(ctx)
	case player.FieldNickname:
		return m.OldNickname(ctx)
	case player.FieldLevel:
		return m.OldLevel(ctx)
	case player.FieldExp:
		return m.OldExp(ctx)
	case player.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case player.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case player.FieldLastLoginAt:
		return m.OldLastLoginAt(ctx)
	case player.FieldGold:
		return m.OldGold(ctx)
	case player.FieldGems:
		return m.OldGems(ctx)
	case player.FieldAdventureID:
		return m.OldAdventureID(ctx)
	case player.FieldStageIndex:
		return m.OldStageIndex(ctx)
	case player.FieldHighestStageCleared:
		return m.OldHighestStageCleared(ctx)
	case player.FieldLastClaimAt:
		return m.OldLastClaimAt(ctx)
	case player.FieldEquipmentJSON:
		return m.OldEquipmentJSON(ctx)
	case player.FieldClearedMilestones:
		return m.OldClearedMilestones(ctx)
	}
	return nil, fmt.Errorf("unknown Player field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PlayerMutation) SetField(name string, value ent.Value) error {
	switch name {
	case player.FieldPlatform:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPlatform(v)
		return nil
	case player.FieldExternalID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExternalID(v)
		return nil
	case player.FieldNickname:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNickname(v)
		return nil
	case player.FieldLevel:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLevel(v)
		return nil
	case player.FieldExp:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExp(v)
		return nil
	case player.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case player.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case player.FieldLastLoginAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastLoginAt(v)
		return nil
	case player.FieldGold:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGold(v)
		return nil
	case player.FieldGems:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGems(v)
		return nil
	case player.FieldAdventureID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAdventureID(v)
		return nil
	case player.FieldStageIndex:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStageIndex(v)
		return nil
	case player.FieldHighestStageCleared:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHighestStageCleared(v)
		return nil
	case player.FieldLastClaimAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastClaimAt(v)
		return nil
	case player.FieldEquipmentJSON:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEquipmentJSON(v)
		return nil
	case player.FieldClearedMilestones:
		v, ok := value.([]int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClearedMilestones(v)
		return nil
	}
	return fmt.Errorf("unknown Player field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PlayerMutation) AddedFields() []string {
	var fields []string
	if m.addlevel != nil {
		fields = append(fields, player.FieldLevel)
	}
	if m.addexp != nil {
		fields = append(fields, player.FieldExp)
	}
	if m.addgold != nil {
		fields = append(fields, player.FieldGold)
	}
	if m.addgems != nil {
		fields = append(fields, player.FieldGems)
	}
	if m.addadventure_id != nil {
		fields = append(fields, player.FieldAdventureID)
	}
	if m.addstage_index != nil {
		fields = append(fields, player.FieldStageIndex)
	}
	if m.addhighest_stage_cleared != nil {
		fields = append(fields, player.FieldHighestStageCleared)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PlayerMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case player.FieldLevel:
		return m.AddedLevel()
	case player.FieldExp:
		return m.AddedExp()
	case player.FieldGold:
		return m.AddedGold()
	case player.FieldGems:
		return m.AddedGems()
	case player.FieldAdventureID:
		return m.AddedAdventureID()
	case player.FieldStageIndex:
		return m.AddedStageIndex()
	case player.FieldHighestStageCleared:
		return m.AddedHighestStageCleared()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PlayerMutation) AddField(name string, value ent.Value) error {
	switch name {
	case player.FieldLevel:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLevel(v)
		return nil
	case player.FieldExp:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddExp(v)
		return nil
	case player.FieldGold:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGold(v)
		return nil
	case player.FieldGems:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGems(v)
		return nil
	case player.FieldAdventureID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAdventureID(v)
		return nil
	case player.FieldStageIndex:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStageIndex(v)
		return nil
	case player.FieldHighestStageCleared:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddHighestStageCleared(v)
		return nil
	}
	return fmt.Errorf("unknown Player numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PlayerMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(player.FieldLastLoginAt) {
		fields = append(fields, player.FieldLastLoginAt)
	}
	if m.FieldCleared(player.FieldLastClaimAt) {
		fields = append(fields, player.FieldLastClaimAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PlayerMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PlayerMutation) ClearField(name string) error {
	switch name {
	case player.FieldLastLoginAt:
		m.ClearLastLoginAt()
		return nil
	case player.FieldLastClaimAt:
		m.ClearLastClaimAt()
		return nil
	}
	return fmt.Errorf("unknown Player nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PlayerMutation) ResetField(name string) error {
	switch name {
	case player.FieldPlatform:
		m.ResetPlatform()
		return nil
	case player.FieldExternalID:
		m.ResetExternalID()
		return nil
	case player.FieldNickname:
		m.ResetNickname()
		return nil
	case player.FieldLevel:
		m.ResetLevel()
		return nil
	case player.FieldExp:
		m.ResetExp()
		return nil
	case player.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case player.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case player.FieldLastLoginAt:
		m.ResetLastLoginAt()
		return nil
	case player.FieldGold:
		m.ResetGold()
		return nil
	case player.FieldGems:
		m.ResetGems()
		return nil
	case player.FieldAdventureID:
		m.ResetAdventureID()
		return nil
	case player.FieldStageIndex:
		m.ResetStageIndex()
		return nil
	case player.FieldHighestStageCleared:
		m.ResetHighestStageCleared()
		return nil
	case player.FieldLastClaimAt:
		m.ResetLastClaimAt()
		return nil
	case player.FieldEquipmentJSON:
		m.ResetEquipmentJSON()
		return nil
	case player.FieldClearedMilestones:
		m.ResetClearedMilestones()
		return nil
	}
	return fmt.Errorf("unknown Player field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PlayerMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PlayerMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PlayerMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PlayerMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PlayerMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PlayerMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PlayerMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Player unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PlayerMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Player edge %s", name)
}
