// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/slimeyquest/server/ent/player"
)

// Player is the model entity for the Player schema.
type Player struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID string `json:"external_id,omitempty"`
	// Nickname holds the value of the "nickname" field.
	Nickname string `json:"nickname,omitempty"`
	// Level holds the value of the "level" field.
	Level int32 `json:"level,omitempty"`
	// Exp holds the value of the "exp" field.
	Exp int64 `json:"exp,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// LastLoginAt holds the value of the "last_login_at" field.
	LastLoginAt *time.Time `json:"last_login_at,omitempty"`
	// Gold holds the value of the "gold" field.
	Gold int64 `json:"gold,omitempty"`
	// Gems holds the value of the "gems" field.
	Gems int64 `json:"gems,omitempty"`
	// AdventureID holds the value of the "adventure_id" field.
	AdventureID int32 `json:"adventure_id,omitempty"`
	// StageIndex holds the value of the "stage_index" field.
	StageIndex int32 `json:"stage_index,omitempty"`
	// HighestStageCleared holds the value of the "highest_stage_cleared" field.
	HighestStageCleared int32 `json:"highest_stage_cleared,omitempty"`
	// LastClaimAt holds the value of the "last_claim_at" field.
	LastClaimAt *time.Time `json:"last_claim_at,omitempty"`
	// EquipmentJSON holds the value of the "equipment_json" field.
	EquipmentJSON map[string]interface{} `json:"equipment_json,omitempty"`
	// ClearedMilestones holds the value of the "cleared_milestones" field.
	ClearedMilestones []int32 `json:"cleared_milestones,omitempty"`
	selectValues      sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Player) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case player.FieldEquipmentJSON, player.FieldClearedMilestones:
			values[i] = new([]byte)
		case player.FieldID, player.FieldLevel, player.FieldExp, player.FieldGold, player.FieldGems, player.FieldAdventureID, player.FieldStageIndex, player.FieldHighestStageCleared:
			values[i] = new(sql.NullInt64)
		case player.FieldPlatform, player.FieldExternalID, player.FieldNickname:
			values[i] = new(sql.NullString)
		case player.FieldCreatedAt, player.FieldUpdatedAt, player.FieldLastLoginAt, player.FieldLastClaimAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Player fields.
func (_m *Player) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case player.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case player.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case player.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = value.String
			}
		case player.FieldNickname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nickname", values[i])
			} else if value.Valid {
				_m.Nickname = value.String
			}
		case player.FieldLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = int32(value.Int64)
			}
		case player.FieldExp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field exp", values[i])
			} else if value.Valid {
				_m.Exp = value.Int64
			}
		case player.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case player.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case player.FieldLastLoginAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_login_at", values[i])
			} else if value.Valid {
				_m.LastLoginAt = new(time.Time)
				*_m.LastLoginAt = value.Time
			}
		case player.FieldGold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gold", values[i])
			} else if value.Valid {
				_m.Gold = value.Int64
			}
		case player.FieldGems:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gems", values[i])
			} else if value.Valid {
				_m.Gems = value.Int64
			}
		case player.FieldAdventureID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field adventure_id", values[i])
			} else if value.Valid {
				_m.AdventureID = int32(value.Int64)
			}
		case player.FieldStageIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stage_index", values[i])
			} else if value.Valid {
				_m.StageIndex = int32(value.Int64)
			}
		case player.FieldHighestStageCleared:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field highest_stage_cleared", values[i])
			} else if value.Valid {
				_m.HighestStageCleared = int32(value.Int64)
			}
		case player.FieldLastClaimAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_claim_at", values[i])
			} else if value.Valid {
				_m.LastClaimAt = new(time.Time)
				*_m.LastClaimAt = value.Time
			}
		case player.FieldEquipmentJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field equipment_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.EquipmentJSON); err != nil {
					return fmt.Errorf("unmarshal field equipment_json: %w", err)
				}
			}
		case player.FieldClearedMilestones:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field cleared_milestones", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ClearedMilestones); err != nil {
					return fmt.Errorf("unmarshal field cleared_milestones: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Player.
// This includes values selected through modifiers, order, etc.
func (_m *Player) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Player.
// Note that you need to call Player.Unwrap() before calling this method if this Player
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Player) Update() *PlayerUpdateOne {
	return NewPlayerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Player entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Player) Unwrap() *Player {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Player is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Player) String() string {
	var builder strings.Builder
	builder.WriteString("Player(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("external_id=")
	builder.WriteString(_m.ExternalID)
	builder.WriteString(", ")
	builder.WriteString("nickname=")
	builder.WriteString(_m.Nickname)
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", _m.Level))
	builder.WriteString(", ")
	builder.WriteString("exp=")
	builder.WriteString(fmt.Sprintf("%v", _m.Exp))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastLoginAt; v != nil {
		builder.WriteString("last_login_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("gold=")
	builder.WriteString(fmt.Sprintf("%v", _m.Gold))
	builder.WriteString(", ")
	builder.WriteString("gems=")
	builder.WriteString(fmt.Sprintf("%v", _m.Gems))
	builder.WriteString(", ")
	builder.WriteString("adventure_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AdventureID))
	builder.WriteString(", ")
	builder.WriteString("stage_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.StageIndex))
	builder.WriteString(", ")
	builder.WriteString("highest_stage_cleared=")
	builder.WriteString(fmt.Sprintf("%v", _m.HighestStageCleared))
	builder.WriteString(", ")
	if v := _m.LastClaimAt; v != nil {
		builder.WriteString("last_claim_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("equipment_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.EquipmentJSON))
	builder.WriteString(", ")
	builder.WriteString("cleared_milestones=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClearedMilestones))
	builder.WriteByte(')')
	return builder.String()
}

// Players is a parsable slice of Player.
type Players []*Player
