// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/slimeyquest/server/ent/player"
	"github.com/slimeyquest/server/ent/predicate"
)

// PlayerUpdate is the builder for updating Player entities.
type PlayerUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerMutation
}

// Where appends a list predicates to the PlayerUpdate builder.
func (_u *PlayerUpdate) Where(ps ...predicate.Player) *PlayerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *PlayerUpdate) SetPlatform(v string) *PlayerUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillablePlatform(v *string) *PlayerUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *PlayerUpdate) SetExternalID(v string) *PlayerUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableExternalID(v *string) *PlayerUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *PlayerUpdate) SetNickname(v string) *PlayerUpdate {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableNickname(v *string) *PlayerUpdate {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *PlayerUpdate) SetLevel(v int32) *PlayerUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableLevel(v *int32) *PlayerUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *PlayerUpdate) AddLevel(v int32) *PlayerUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// SetExp sets the "exp" field.
func (_u *PlayerUpdate) SetExp(v int64) *PlayerUpdate {
	_u.mutation.ResetExp()
	_u.mutation.SetExp(v)
	return _u
}

// SetNillableExp sets the "exp" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableExp(v *int64) *PlayerUpdate {
	if v != nil {
		_u.SetExp(*v)
	}
	return _u
}

// AddExp adds value to the "exp" field.
func (_u *PlayerUpdate) AddExp(v int64) *PlayerUpdate {
	_u.mutation.AddExp(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlayerUpdate) SetUpdatedAt(v time.Time) *PlayerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *PlayerUpdate) SetLastLoginAt(v time.Time) *PlayerUpdate {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableLastLoginAt(v *time.Time) *PlayerUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *PlayerUpdate) ClearLastLoginAt() *PlayerUpdate {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// Mutation returns the PlayerMutation object of the builder.
func (_u *PlayerUpdate) Mutation() *PlayerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlayerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlayerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlayerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := player.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := player.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Player.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := player.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "Player.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nickname(); ok {
		if err := player.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "Player.nickname": %w`, err)}
		}
	}
	return nil
}

func (_u *PlayerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(player.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(player.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(player.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(player.FieldLevel, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(player.FieldLevel, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Exp(); ok {
		_spec.SetField(player.FieldExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExp(); ok {
		_spec.AddField(player.FieldExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(player.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(player.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(player.FieldLastLoginAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlayerUpdateOne is the builder for updating a single Player entity.
type PlayerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerMutation
}

// SetPlatform sets the "platform" field.
func (_u *PlayerUpdateOne) SetPlatform(v string) *PlayerUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillablePlatform(v *string) *PlayerUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *PlayerUpdateOne) SetExternalID(v string) *PlayerUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableExternalID(v *string) *PlayerUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *PlayerUpdateOne) SetNickname(v string) *PlayerUpdateOne {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableNickname(v *string) *PlayerUpdateOne {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *PlayerUpdateOne) SetLevel(v int32) *PlayerUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableLevel(v *int32) *PlayerUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *PlayerUpdateOne) AddLevel(v int32) *PlayerUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// SetExp sets the "exp" field.
func (_u *PlayerUpdateOne) SetExp(v int64) *PlayerUpdateOne {
	_u.mutation.ResetExp()
	_u.mutation.SetExp(v)
	return _u
}

// SetNillableExp sets the "exp" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableExp(v *int64) *PlayerUpdateOne {
	if v != nil {
		_u.SetExp(*v)
	}
	return _u
}

// AddExp adds value to the "exp" field.
func (_u *PlayerUpdateOne) AddExp(v int64) *PlayerUpdateOne {
	_u.mutation.AddExp(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlayerUpdateOne) SetUpdatedAt(v time.Time) *PlayerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *PlayerUpdateOne) SetLastLoginAt(v time.Time) *PlayerUpdateOne {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableLastLoginAt(v *time.Time) *PlayerUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *PlayerUpdateOne) ClearLastLoginAt() *PlayerUpdateOne {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// Mutation returns the PlayerMutation object of the builder.
func (_u *PlayerUpdateOne) Mutation() *PlayerMutation {
	return _u.mutation
}

// Where appends a list predicates to the PlayerUpdate builder.
func (_u *PlayerUpdateOne) Where(ps ...predicate.Player) *PlayerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlayerUpdateOne) Select(field string, fields ...string) *PlayerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Player entity.
func (_u *PlayerUpdateOne) Save(ctx context.Context) (*Player, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpdateOne) SaveX(ctx context.Context) *Player {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlayerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlayerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := player.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := player.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Player.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := player.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "Player.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nickname(); ok {
		if err := player.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "Player.nickname": %w`, err)}
		}
	}
	return nil
}

func (_u *PlayerUpdateOne) sqlSave(ctx context.Context) (_node *Player, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Player.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, player.FieldID)
		for _, f := range fields {
			if !player.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != player.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(player.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(player.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(player.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(player.FieldLevel, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(player.FieldLevel, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Exp(); ok {
		_spec.SetField(player.FieldExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExp(); ok {
		_spec.AddField(player.FieldExp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(player.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(player.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(player.FieldLastLoginAt, field.TypeTime)
	}
	_node = &Player{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
