// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/slimeyquest/server/ent/player"
	"github.com/slimeyquest/server/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	playerFields := schema.Player{}.Fields()
	_ = playerFields
	// playerDescPlatform is the schema descriptor for platform field.
	playerDescPlatform := playerFields[0].Descriptor()
	// player.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	player.PlatformValidator = playerDescPlatform.Validators[0].(func(string) error)
	// playerDescExternalID is the schema descriptor for external_id field.
	playerDescExternalID := playerFields[1].Descriptor()
	// player.ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	player.ExternalIDValidator = playerDescExternalID.Validators[0].(func(string) error)
	// playerDescNickname is the schema descriptor for nickname field.
	playerDescNickname := playerFields[2].Descriptor()
	// player.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	player.NicknameValidator = playerDescNickname.Validators[0].(func(string) error)
	// playerDescLevel is the schema descriptor for level field.
	playerDescLevel := playerFields[3].Descriptor()
	// player.DefaultLevel holds the default value on creation for the level field.
	player.DefaultLevel = playerDescLevel.Default.(int32)
	// playerDescExp is the schema descriptor for exp field.
	playerDescExp := playerFields[4].Descriptor()
	// player.DefaultExp holds the default value on creation for the exp field.
	player.DefaultExp = playerDescExp.Default.(int64)
	// playerDescCreatedAt is the schema descriptor for created_at field.
	playerDescCreatedAt := playerFields[5].Descriptor()
	// player.DefaultCreatedAt holds the default value on creation for the created_at field.
	player.DefaultCreatedAt = playerDescCreatedAt.Default.(func() time.Time)
	// playerDescUpdatedAt is the schema descriptor for updated_at field.
	playerDescUpdatedAt := playerFields[6].Descriptor()
	// player.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	player.DefaultUpdatedAt = playerDescUpdatedAt.Default.(func() time.Time)
	// player.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	player.UpdateDefaultUpdatedAt = playerDescUpdatedAt.UpdateDefault.(func() time.Time)
}
