// Code generated by ent, DO NOT EDIT.

package player

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the player type in the database.
	Label = "player"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldExternalID holds the string denoting the external_id field in the database.
	FieldExternalID = "external_id"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldExp holds the string denoting the exp field in the database.
	FieldExp = "exp"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldLastLoginAt holds the string denoting the last_login_at field in the database.
	FieldLastLoginAt = "last_login_at"
	// FieldGold holds the string denoting the gold field in the database.
	FieldGold = "gold"
	// FieldGems holds the string denoting the gems field in the database.
	FieldGems = "gems"
	// FieldAdventureID holds the string denoting the adventure_id field in the database.
	FieldAdventureID = "adventure_id"
	// FieldStageIndex holds the string denoting the stage_index field in the database.
	FieldStageIndex = "stage_index"
	// FieldHighestStageCleared holds the string denoting the highest_stage_cleared field in the database.
	FieldHighestStageCleared = "highest_stage_cleared"
	// FieldLastClaimAt holds the string denoting the last_claim_at field in the database.
	FieldLastClaimAt = "last_claim_at"
	// FieldEquipmentJSON holds the string denoting the equipment_json field in the database.
	FieldEquipmentJSON = "equipment_json"
	// FieldClearedMilestones holds the string denoting the cleared_milestones field in the database.
	FieldClearedMilestones = "cleared_milestones"
	// Table holds the table name of the player in the database.
	Table = "players"
)

// Columns holds all SQL columns for player fields.
var Columns = []string{
	FieldID,
	FieldPlatform,
	FieldExternalID,
	FieldNickname,
	FieldLevel,
	FieldExp,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldLastLoginAt,
	FieldGold,
	FieldGems,
	FieldAdventureID,
	FieldStageIndex,
	FieldHighestStageCleared,
	FieldLastClaimAt,
	FieldEquipmentJSON,
	FieldClearedMilestones,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	ExternalIDValidator func(string) error
	// NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	NicknameValidator func(string) error
	// DefaultLevel holds the default value on creation for the "level" field.
	DefaultLevel int32
	// DefaultExp holds the default value on creation for the "exp" field.
	DefaultExp int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultGold holds the default value on creation for the "gold" field.
	DefaultGold int64
	// DefaultGems holds the default value on creation for the "gems" field.
	DefaultGems int64
	// DefaultAdventureID holds the default value on creation for the "adventure_id" field.
	DefaultAdventureID int32
	// DefaultStageIndex holds the default value on creation for the "stage_index" field.
	DefaultStageIndex int32
	// DefaultHighestStageCleared holds the default value on creation for the "highest_stage_cleared" field.
	DefaultHighestStageCleared int32
	// DefaultEquipmentJSON holds the default value on creation for the "equipment_json" field.
	DefaultEquipmentJSON map[string]interface{}
	// DefaultClearedMilestones holds the default value on creation for the "cleared_milestones" field.
	DefaultClearedMilestones []int32
)

// OrderOption defines the ordering options for the Player queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByExternalID orders the results by the external_id field.
func ByExternalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalID, opts...).ToFunc()
}

// ByNickname orders the results by the nickname field.
func ByNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNickname, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByExp orders the results by the exp field.
func ByExp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExp, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLastLoginAt orders the results by the last_login_at field.
func ByLastLoginAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLoginAt, opts...).ToFunc()
}

// ByGold orders the results by the gold field.
func ByGold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGold, opts...).ToFunc()
}

// ByGems orders the results by the gems field.
func ByGems(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGems, opts...).ToFunc()
}

// ByAdventureID orders the results by the adventure_id field.
func ByAdventureID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdventureID, opts...).ToFunc()
}

// ByStageIndex orders the results by the stage_index field.
func ByStageIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStageIndex, opts...).ToFunc()
}

// ByHighestStageCleared orders the results by the highest_stage_cleared field.
func ByHighestStageCleared(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHighestStageCleared, opts...).ToFunc()
}

// ByLastClaimAt orders the results by the last_claim_at field.
func ByLastClaimAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastClaimAt, opts...).ToFunc()
}
