// Code generated by ent, DO NOT EDIT.

package player

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/slimeyquest/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldID, id))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldPlatform, v))
}

// ExternalID applies equality check predicate on the "external_id" field. It's identical to ExternalIDEQ.
func ExternalID(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldExternalID, v))
}

// Nickname applies equality check predicate on the "nickname" field. It's identical to NicknameEQ.
func Nickname(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldNickname, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v int32) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLevel, v))
}

// Exp applies equality check predicate on the "exp" field. It's identical to ExpEQ.
func Exp(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldExp, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldUpdatedAt, v))
}

// LastLoginAt applies equality check predicate on the "last_login_at" field. It's identical to LastLoginAtEQ.
func LastLoginAt(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLastLoginAt, v))
}

// Gold applies equality check predicate on the "gold" field. It's identical to GoldEQ.
func Gold(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldGold, v))
}

// Gems applies equality check predicate on the "gems" field. It's identical to GemsEQ.
func Gems(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldGems, v))
}

// AdventureID applies equality check predicate on the "adventure_id" field. It's identical to AdventureIDEQ.
func AdventureID(v int32) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldAdventureID, v))
}

// StageIndex applies equality check predicate on the "stage_index" field. It's identical to StageIndexEQ.
func StageIndex(v int32) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldStageIndex, v))
}

// HighestStageCleared applies equality check predicate on the "highest_stage_cleared" field. It's identical to HighestStageClearedEQ.
func HighestStageCleared(v int32) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldHighestStageCleared, v))
}

// LastClaimAt applies equality check predicate on the "last_claim_at" field. It's identical to LastClaimAtEQ.
func LastClaimAt(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLastClaimAt, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.Player {
	return predicate.Player(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.Player {
	return predicate.Player(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.Player {
	return predicate.Player(sql.FieldContainsFold(FieldPlatform, v))
}

// ExternalIDEQ applies the EQ predicate on the "external_id" field.
func ExternalIDEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldExternalID, v))
}

// ExternalIDNEQ applies the NEQ predicate on the "external_id" field.
func ExternalIDNEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldExternalID, v))
}

// ExternalIDIn applies the In predicate on the "external_id" field.
func ExternalIDIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldExternalID, vs...))
}

// ExternalIDNotIn applies the NotIn predicate on the "external_id" field.
func ExternalIDNotIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldExternalID, vs...))
}

// ExternalIDGT applies the GT predicate on the "external_id" field.
func ExternalIDGT(v string) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldExternalID, v))
}

// ExternalIDGTE applies the GTE predicate on the "external_id" field.
func ExternalIDGTE(v string) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldExternalID, v))
}

// ExternalIDLT applies the LT predicate on the "external_id" field.
func ExternalIDLT(v string) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldExternalID, v))
}

// ExternalIDLTE applies the LTE predicate on the "external_id" field.
func ExternalIDLTE(v string) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldExternalID, v))
}

// ExternalIDContains applies the Contains predicate on the "external_id" field.
func ExternalIDContains(v string) predicate.Player {
	return predicate.Player(sql.FieldContains(FieldExternalID, v))
}

// ExternalIDHasPrefix applies the HasPrefix predicate on the "external_id" field.
func ExternalIDHasPrefix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasPrefix(FieldExternalID, v))
}

// ExternalIDHasSuffix applies the HasSuffix predicate on the "external_id" field.
func ExternalIDHasSuffix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasSuffix(FieldExternalID, v))
}

// ExternalIDEqualFold applies the EqualFold predicate on the "external_id" field.
func ExternalIDEqualFold(v string) predicate.Player {
	return predicate.Player(sql.FieldEqualFold(FieldExternalID, v))
}

// ExternalIDContainsFold applies the ContainsFold predicate on the "external_id" field.
func ExternalIDContainsFold(v string) predicate.Player {
	return predicate.Player(sql.FieldContainsFold(FieldExternalID, v))
}

// NicknameEQ applies the EQ predicate on the "nickname" field.
func NicknameEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldNickname, v))
}

// NicknameNEQ applies the NEQ predicate on the "nickname" field.
func NicknameNEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldNickname, v))
}

// NicknameIn applies the In predicate on the "nickname" field.
func NicknameIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldNickname, vs...))
}

// NicknameNotIn applies the NotIn predicate on the "nickname" field.
func NicknameNotIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldNickname, vs...))
}

// NicknameGT applies the GT predicate on the "nickname" field.
func NicknameGT(v string) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldNickname, v))
}

// NicknameGTE applies the GTE predicate on the "nickname" field.
func NicknameGTE(v string) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldNickname, v))
}

// NicknameLT applies the LT predicate on the "nickname" field.
func NicknameLT(v string) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldNickname, v))
}

// NicknameLTE applies the LTE predicate on the "nickname" field.
func NicknameLTE(v string) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldNickname, v))
}

// NicknameContains applies the Contains predicate on the "nickname" field.
func NicknameContains(v string) predicate.Player {
	return predicate.Player(sql.FieldContains(FieldNickname, v))
}

// NicknameHasPrefix applies the HasPrefix predicate on the "nickname" field.
func NicknameHasPrefix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasPrefix(FieldNickname, v))
}

// NicknameHasSuffix applies the HasSuffix predicate on the "nickname" field.
func NicknameHasSuffix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasSuffix(FieldNickname, v))
}

// NicknameEqualFold applies the EqualFold predicate on the "nickname" field.
func NicknameEqualFold(v string) predicate.Player {
	return predicate.Player(sql.FieldEqualFold(FieldNickname, v))
}

// NicknameContainsFold applies the ContainsFold predicate on the "nickname" field.
func NicknameContainsFold(v string) predicate.Player {
	return predicate.Player(sql.FieldContainsFold(FieldNickname, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v int32) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v int32) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...int32) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...int32) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v int32) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v int32) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v int32) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v int32) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldLevel, v))
}

// ExpEQ applies the EQ predicate on the "exp" field.
func ExpEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldExp, v))
}

// ExpNEQ applies the NEQ predicate on the "exp" field.
func ExpNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldExp, v))
}

// ExpIn applies the In predicate on the "exp" field.
func ExpIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldExp, vs...))
}

// ExpNotIn applies the NotIn predicate on the "exp" field.
func ExpNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldExp, vs...))
}

// ExpGT applies the GT predicate on the "exp" field.
func ExpGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldExp, v))
}

// ExpGTE applies the GTE predicate on the "exp" field.
func ExpGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldExp, v))
}

// ExpLT applies the LT predicate on the "exp" field.
func ExpLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldExp, v))
}

// ExpLTE applies the LTE predicate on the "exp" field.
func ExpLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldExp, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldUpdatedAt, v))
}

// LastLoginAtEQ applies the EQ predicate on the "last_login_at" field.
func LastLoginAtEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastLoginAtNEQ applies the NEQ predicate on the "last_login_at" field.
func LastLoginAtNEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldLastLoginAt, v))
}

// LastLoginAtIn applies the In predicate on the "last_login_at" field.
func LastLoginAtIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldLastLoginAt, vs...))
}

// LastLoginAtNotIn applies the NotIn predicate on the "last_login_at" field.
func LastLoginAtNotIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldLastLoginAt, vs...))
}

// LastLoginAtGT applies the GT predicate on the "last_login_at" field.
func LastLoginAtGT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldLastLoginAt, v))
}

// LastLoginAtGTE applies the GTE predicate on the "last_login_at" field.
func LastLoginAtGTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldLastLoginAt, v))
}

// LastLoginAtLT applies the LT predicate on the "last_login_at" field.
func LastLoginAtLT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldLastLoginAt, v))
}

// LastLoginAtLTE applies the LTE predicate on the "last_login_at" field.
func LastLoginAtLTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldLastLoginAt, v))
}

// LastLoginAtIsNil applies the IsNil predicate on the "last_login_at" field.
func LastLoginAtIsNil() predicate.Player {
	return predicate.Player(sql.FieldIsNull(FieldLastLoginAt))
}

// LastLoginAtNotNil applies the NotNil predicate on the "last_login_at" field.
func LastLoginAtNotNil() predicate.Player {
	return predicate.Player(sql.FieldNotNull(FieldLastLoginAt))
}

// GoldEQ applies the EQ predicate on the "gold" field.
func GoldEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldGold, v))
}

// GoldNEQ applies the NEQ predicate on the "gold" field.
func GoldNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldGold, v))
}

// GoldIn applies the In predicate on the "gold" field.
func GoldIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldGold, vs...))
}

// GoldNotIn applies the NotIn predicate on the "gold" field.
func GoldNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldGold, vs...))
}

// GoldGT applies the GT predicate on the "gold" field.
func GoldGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldGold, v))
}

// GoldGTE applies the GTE predicate on the "gold" field.
func GoldGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldGold, v))
}

// GoldLT applies the LT predicate on the "gold" field.
func GoldLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldGold, v))
}

// GoldLTE applies the LTE predicate on the "gold" field.
func GoldLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldGold, v))
}

// GemsEQ applies the EQ predicate on the "gems" field.
func GemsEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldGems, v))
}

// GemsNEQ applies the NEQ predicate on the "gems" field.
func GemsNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldGems, v))
}

// GemsIn applies the In predicate on the "gems" field.
func GemsIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldGems, vs...))
}

// GemsNotIn applies the NotIn predicate on the "gems" field.
func GemsNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldGems, vs...))
}

// GemsGT applies the GT predicate on the "gems" field.
func GemsGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldGems, v))
}

// GemsGTE applies the GTE predicate on the "gems" field.
func GemsGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldGems, v))
}

// GemsLT applies the LT predicate on the "gems" field.
func GemsLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldGems, v))
}

// GemsLTE applies the LTE predicate on the "gems" field.
func GemsLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldGems, v))
}

// AdventureIDEQ applies the EQ predicate on the "adventure_id" field.
func AdventureIDEQ(v int32) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldAdventureID, v))
}

// AdventureIDNEQ applies the NEQ predicate on the "adventure_id" field.
func AdventureIDNEQ(v int32) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldAdventureID, v))
}

// AdventureIDIn applies the In predicate on the "adventure_id" field.
func AdventureIDIn(vs ...int32) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldAdventureID, vs...))
}

// AdventureIDNotIn applies the NotIn predicate on the "adventure_id" field.
func AdventureIDNotIn(vs ...int32) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldAdventureID, vs...))
}

// AdventureIDGT applies the GT predicate on the "adventure_id" field.
func AdventureIDGT(v int32) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldAdventureID, v))
}

// AdventureIDGTE applies the GTE predicate on the "adventure_id" field.
func AdventureIDGTE(v int32) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldAdventureID, v))
}

// AdventureIDLT applies the LT predicate on the "adventure_id" field.
func AdventureIDLT(v int32) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldAdventureID, v))
}

// AdventureIDLTE applies the LTE predicate on the "adventure_id" field.
func AdventureIDLTE(v int32) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldAdventureID, v))
}

// StageIndexEQ applies the EQ predicate on the "stage_index" field.
func StageIndexEQ(v int32) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldStageIndex, v))
}

// StageIndexNEQ applies the NEQ predicate on the "stage_index" field.
func StageIndexNEQ(v int32) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldStageIndex, v))
}

// StageIndexIn applies the In predicate on the "stage_index" field.
func StageIndexIn(vs ...int32) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldStageIndex, vs...))
}

// StageIndexNotIn applies the NotIn predicate on the "stage_index" field.
func StageIndexNotIn(vs ...int32) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldStageIndex, vs...))
}

// StageIndexGT applies the GT predicate on the "stage_index" field.
func StageIndexGT(v int32) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldStageIndex, v))
}

// StageIndexGTE applies the GTE predicate on the "stage_index" field.
func StageIndexGTE(v int32) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldStageIndex, v))
}

// StageIndexLT applies the LT predicate on the "stage_index" field.
func StageIndexLT(v int32) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldStageIndex, v))
}

// StageIndexLTE applies the LTE predicate on the "stage_index" field.
func StageIndexLTE(v int32) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldStageIndex, v))
}

// HighestStageClearedEQ applies the EQ predicate on the "highest_stage_cleared" field.
func HighestStageClearedEQ(v int32) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldHighestStageCleared, v))
}

// HighestStageClearedNEQ applies the NEQ predicate on the "highest_stage_cleared" field.
func HighestStageClearedNEQ(v int32) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldHighestStageCleared, v))
}

// HighestStageClearedIn applies the In predicate on the "highest_stage_cleared" field.
func HighestStageClearedIn(vs ...int32) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldHighestStageCleared, vs...))
}

// HighestStageClearedNotIn applies the NotIn predicate on the "highest_stage_cleared" field.
func HighestStageClearedNotIn(vs ...int32) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldHighestStageCleared, vs...))
}

// HighestStageClearedGT applies the GT predicate on the "highest_stage_cleared" field.
func HighestStageClearedGT(v int32) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldHighestStageCleared, v))
}

// HighestStageClearedGTE applies the GTE predicate on the "highest_stage_cleared" field.
func HighestStageClearedGTE(v int32) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldHighestStageCleared, v))
}

// HighestStageClearedLT applies the LT predicate on the "highest_stage_cleared" field.
func HighestStageClearedLT(v int32) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldHighestStageCleared, v))
}

// HighestStageClearedLTE applies the LTE predicate on the "highest_stage_cleared" field.
func HighestStageClearedLTE(v int32) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldHighestStageCleared, v))
}

// LastClaimAtEQ applies the EQ predicate on the "last_claim_at" field.
func LastClaimAtEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLastClaimAt, v))
}

// LastClaimAtNEQ applies the NEQ predicate on the "last_claim_at" field.
func LastClaimAtNEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldLastClaimAt, v))
}

// LastClaimAtIn applies the In predicate on the "last_claim_at" field.
func LastClaimAtIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldLastClaimAt, vs...))
}

// LastClaimAtNotIn applies the NotIn predicate on the "last_claim_at" field.
func LastClaimAtNotIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldLastClaimAt, vs...))
}

// LastClaimAtGT applies the GT predicate on the "last_claim_at" field.
func LastClaimAtGT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldLastClaimAt, v))
}

// LastClaimAtGTE applies the GTE predicate on the "last_claim_at" field.
func LastClaimAtGTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldLastClaimAt, v))
}

// LastClaimAtLT applies the LT predicate on the "last_claim_at" field.
func LastClaimAtLT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldLastClaimAt, v))
}

// LastClaimAtLTE applies the LTE predicate on the "last_claim_at" field.
func LastClaimAtLTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldLastClaimAt, v))
}

// LastClaimAtIsNil applies the IsNil predicate on the "last_claim_at" field.
func LastClaimAtIsNil() predicate.Player {
	return predicate.Player(sql.FieldIsNull(FieldLastClaimAt))
}

// LastClaimAtNotNil applies the NotNil predicate on the "last_claim_at" field.
func LastClaimAtNotNil() predicate.Player {
	return predicate.Player(sql.FieldNotNull(FieldLastClaimAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Player) predicate.Player {
	return predicate.Player(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Player) predicate.Player {
	return predicate.Player(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Player) predicate.Player {
	return predicate.Player(sql.NotPredicates(p))
}
